name: Agent Recruitment

on: push

jobs:
  recruitment-report:
    runs-on: ubuntu-latest

    steps:
      - name: The agent introduces himself
        run: echo "I am Lex Luthor, and I am the leader of the Legion of Evil"

      - name: Identity Report
        run: |
          echo "============================================"
          echo ""
          echo "Code name: ${{ github.actor }}"
          echo "GitHub Context"
          echo "Repository: ${{ github.repository }}"
          echo "Operation: ${{ github.sha }}"
          echo "Metadata: ${{ toJSON(github) }}"
