name: Legion Spokesperson

on:
  workflow_dispatch:
    inputs:
      villain:
        description: "Which villain is sending the message?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Magneto
          - Joker
          - Mystique
          - Brainiac

      message:
        description: "Message to the Board"
        required: true
        default: "The mission was a success"

      priority:
        description: "Priority Level"
        required: true
        type: choice
        options:
          - 🟢 Normal
          - 🟡 High
          - 🔴 Critical

jobs:
  send-a-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
