name: Legion Spokesperson

on:
  workflow_dispatch:
    inputs:
      villain:
        description: "Which villain is sending the message?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Magneto
          - Joker
          - Mystique
          - Brainiac

      message:
        description: "Message to the Board"
        required: true
        default: "The mission was a success"

      cow_character:
        description: "Character"
        required: true
        type: choice
        options:
          - eyes
          - ghostbusters
          - dragon
          - fox
          - king

      priority:
        description: "Priority Level"
        required: true
        type: choice
        options:
          - 🟢 Normal
          - 🟡 High
          - 🔴 Critical

jobs:
  send-a-message:
    runs-on: ubuntu-latest

    steps:
      - name: Install the Legion Transmitter
        run: sudo apt-get install -y cowsay

      - name: Print inputs
        run: |
          echo "============================"
          echo "  Intercepted Transmission  "
          echo "============================"
          echo ""
          echo "From: ${{ inputs.villain }}"
          echo ""
          echo "Date: $(date -u +"%d/%m/%Y - %H:%M UTC")"
          echo "--------- Message ---------"
          cowsay -f "${{ inputs.cow_character }}" "${{ inputs.message }}"
          echo ""
          echo "--- ${{ inputs.villain }}"
          echo "..."
